Autoresponses
aternosorg/modbot pull request #106
Opened 2020-09-18 14:39 UTC by JulianVennen

2020-09-24 20:09 UTC, KurtThiemann approved these changes

2020-09-26 01:44 UTC, matthi4s requested changes
In general, I'm not really happy with this long spaghetti code in the command and storing all auto-responses in the guild config is not really a good solution.

2020-09-26 01:44 UTC, matthi4s commented on commands/autoresponse.js
> +                .setTitle("Added new auto-response")
?

2020-09-26 01:44 UTC, matthi4s commented on commands/autoresponse.js
> +            await message.channel.send("Do you really want to delete this response?",new Discord.MessageEmbed()
?

2020-09-26 01:44 UTC, matthi4s commented on commands/autoresponse.js
> +                .setTitle("Added new auto-response")
?

2020-10-01 10:22 UTC, matthi4s requested changes
I think at least the channel/global option should be a dedicated column. You can also only load the responses for the current channel then.

2020-10-07 20:05 UTC, JulianVennen commented
Now the only thing that is stored as JSON is the trigger

2020-10-08 15:18 UTC, JulianVennen commented
removing a response still refreshes the cache. Should I change that?

2020-10-08 15:19 UTC, matthi4s commented
Just remove the response from cache?

2020-10-08 15:30 UTC, JulianVennen commented
alright.
Anything else?

2020-10-09 20:26 UTC, KurtThiemann approved these changes

2020-10-10 11:37 UTC, KurtThiemann approved these changes

2020-10-10 14:38 UTC, matthi4s requested changes

2020-10-10 14:38 UTC, matthi4s commented on commands/autoresponse.js
> +    let responses = await util.getAutoResponses(message.channel.id, message.guild.id);
You are loading channel-specific responses here, even though you should load all for the guild.

2020-10-10 19:25 UTC, matthi4s requested changes

2020-10-10 19:25 UTC, matthi4s commented on commands/autoresponse.js
> +        case "info":
```suggestion
        case 'info':
```

2020-10-10 19:25 UTC, matthi4s commented on commands/autoresponse/add.js
> +    await message.channel.send(util.responseEmbed(response,"Added new auto-response",util.color.green));
```suggestion
    await message.channel.send(util.responseEmbed(response,"Added new autoresponse",util.color.green));
```

2020-10-10 19:25 UTC, matthi4s commented on commands/autoresponse/info.js
> +        await message.channel.send("Provide the id of the response you want to view");
```suggestion
        await message.channel.send("Provide the id of the autoresponse you want to view");
```

2020-10-10 19:25 UTC, matthi4s commented on commands/autoresponse/info.js
> +    await message.channel.send(util.responseEmbed(response,"Auto-response",util.color.green));
```suggestion
    await message.channel.send(util.responseEmbed(response,"Autoresponse",util.color.green));
```

2020-10-10 19:25 UTC, matthi4s commented on commands/autoresponse/list.js
> +        return await message.channel.send("No auto-responses!");
```suggestion
        return await message.channel.send("No autoresponses!");
```

2020-10-10 19:25 UTC, matthi4s commented on commands/autoresponse/remove.js
> +        await message.channel.send("Provide the id of the response you want to remove");
```suggestion
        await message.channel.send("Provide the id of the autoresponse you want to remove");
```

2020-10-10 19:25 UTC, matthi4s commented on commands/autoresponse/remove.js
> +    let confirmation = await message.channel.send("Do you really want to delete this response?", util.responseEmbed(response,"Remove auto-response", util.color.red));
```suggestion
    let confirmation = await message.channel.send("Do you really want to delete this autoresponse?", util.responseEmbed(response,"Remove autoresponse", util.color.red));
```

2020-10-10 19:25 UTC, matthi4s commented on commands/autoresponse/remove.js
> +    await message.channel.send(`Removed the response with the id ${response.id}!`);
```suggestion
    await message.channel.send(`Removed the autoresponse with the id ${response.id}!`);
```

2020-10-20 13:55 UTC, matthi4s approved these changes

2020-10-20 14:29 UTC, KurtThiemann approved these changes

2020-10-20 14:30 UTC, merged