Caps lock automoderation
aternosorg/modbot pull request #138
Opened 2020-11-16 20:21 UTC by JulianVennen

2020-11-20 17:11 UTC, matthi4s requested changes

2020-11-20 17:11 UTC, matthi4s commented on src/features/message/caps.js
> +        const response = await message.reply('don\'t use so many caps!')
I don't like that message, but I also don't know what's a proper English message for that. It also should follow the same scheme as other error messages, maybe create a util function for all errors which creates a red embed?

2020-11-24 15:10 UTC, matthi4s requested changes

2020-11-24 15:10 UTC, matthi4s commented on src/features/message/caps.js
> +        const response = await message.channel.send(`<@!${message.author.id} don't use that many capital letters!`)
```suggestion
        const response = await message.channel.send(`<@!${message.author.id} Don't use that many capital letters!`)
```

2020-11-24 15:10 UTC, matthi4s commented on src/features/message/invitemod.js
> +    let response = await message.channel.send(`<@!${message.author.id}> invites are not allowed here!`);
```suggestion
    let response = await message.channel.send(`<@!${message.author.id}> Invites are not allowed here!`);
```

2020-11-24 15:15 UTC, matthi4s approved these changes

2020-11-24 17:42 UTC, KurtThiemann approved these changes

2020-11-24 17:43 UTC, Drachionix approved these changes

2020-11-27 08:52 UTC, merged