retry locking/unlocking
aternosorg/modbot pull request #147
Opened 2020-12-03 18:01 UTC by JulianVennen

2020-12-08 09:38 UTC, KurtThiemann requested changes

2020-12-08 09:38 UTC, KurtThiemann commented on src/commands/unlock.js
> +        console.log('denied')
Maybe remove those log messages or change them to something more descriptive

2020-12-08 09:38 UTC, KurtThiemann commented on src/commands/unlock.js
> +        console.log('not allowed')
+1

2020-12-14 11:28 UTC, matthi4s approved these changes

2020-12-14 17:53 UTC, KurtThiemann approved these changes

2020-12-14 23:05 UTC, KurtThiemann approved these changes

2020-12-15 15:20 UTC, matthi4s approved these changes

2020-12-15 15:20 UTC, merged