Allowed mentions
aternosorg/modbot pull request #154
Opened 2020-12-20 15:26 UTC by BluewyDev

(Dont know if i did this exactly correct)
This should disable any pings from anything by default, yes, it will show the pings but it wont actually ping.

2020-12-20 20:12 UTC, Fedes10 approved these changes

2020-12-20 20:15 UTC, Fedes10 requested changes
I think is -

2020-12-20 20:50 UTC, BluewyDev commented
> I think is -

Can't really do much with this unfortunately.

I'll however test this out further, if i find this works without turning mentions into a mess i will reopen the pr.

2020-12-20 20:50 UTC, closed without merging

2020-12-21 00:45 UTC, Fedes10 commented
Okey,  Better this way