update README
aternosorg/modbot pull request #160
Opened 2020-12-22 19:55 UTC by JulianVennen

2020-12-23 13:36 UTC, matthi4s submitted a review, later dismissed

2020-12-28 16:57 UTC, matthi4s requested changes

2020-12-28 16:57 UTC, matthi4s commented on README.md
> +0. Create a [Discord application](https://discordapp.com/developers/applications/)
```suggestion
2. Create a [Discord application](https://discordapp.com/developers/applications/)
```

2020-12-28 16:57 UTC, matthi4s commented on README.md
> +0. Add a bot to the application and copy the auth token
```suggestion
3. Add a bot to the application and copy the auth token
```

2020-12-28 16:57 UTC, matthi4s commented on README.md
> +0. Create an API key in the [Google Cloud Console](https://console.cloud.google.com/) for the Youtube Data API v3
```suggestion
4. Create an API key in the [Google Cloud Console](https://console.cloud.google.com/) for the Youtube Data API v3
```

2020-12-28 16:57 UTC, matthi4s commented on README.md
> +0. Copy the example.config.json to config.json, and configure it
```suggestion
5. Copy the example.config.json to config.json, and configure it
```

2020-12-28 16:57 UTC, matthi4s commented on README.md
> +0. Start the index.js file
```suggestion
6. Start the index.js file
```

2020-12-28 16:57 UTC, matthi4s commented on README.md
> +0. To invite the bot to your server replace `ID` with the client ID of your application https://discordapp.com/oauth2/authorize?client_id=ID&scope=bot&permissions=268446806 and open the link
```suggestion
7. To invite the bot to your server replace `ID` with the client ID of your application https://discordapp.com/oauth2/authorize?client_id=ID&scope=bot&permissions=268446806 and open the link
```

2020-12-30 20:34 UTC, KurtThiemann approved these changes

2021-01-04 15:38 UTC, matthi4s approved these changes

2021-01-04 15:39 UTC, merged