Add DM punishment
aternosorg/modbot pull request #167
Opened 2021-01-05 16:06 UTC by JulianVennen

2021-01-09 16:45 UTC, KurtThiemann submitted a review, later dismissed

2021-01-09 16:52 UTC, matthi4s requested changes

2021-01-09 16:52 UTC, matthi4s commented on src/commands/strike.js
> +        await user.send(punishment.message);
```suggestion
        await user.send('Your message in `${guild.name}` was removed: ' + punishment.message);
```

2021-01-15 12:01 UTC, matthi4s approved these changes

2021-01-15 18:51 UTC, KurtThiemann approved these changes

2021-01-15 18:51 UTC, merged