add anti-raid-mode
aternosorg/modbot pull request #193
Opened 2021-02-09 16:17 UTC by JulianVennen

2021-02-11 15:51 UTC, matthi4s requested changes

2021-02-11 15:51 UTC, matthi4s commented on src/commands/moderation/raidmode.js
> +    static description = 'en/disable anti-raid-mode';
```suggestion
    static description = 'En-/disable anti-raid-mode (Kicks everybody that joins while enabled).';
```

2021-02-11 15:51 UTC, matthi4s commented on src/commands/moderation/raidmode.js
> +                await this.message.channel.send("Enabled anti-raid-mode!");
```suggestion
                await this.message.channel.send("Enabled anti-raid-mode! Nobody can join this server now.");
```

2021-02-11 17:32 UTC, matthi4s approved these changes

2021-02-19 22:01 UTC, KurtThiemann approved these changes

2021-02-19 22:02 UTC, matthi4s approved these changes

2021-02-19 22:02 UTC, merged