refactor ban command
aternosorg/modbot pull request #202
Opened 2021-02-20 16:05 UTC by JulianVennen

- adds the class ModerationCommand which implements shared code of all moderation commands
- adds TimedModerationCommand for moderation commands with a duration

2021-02-20 18:07 UTC, matthi4s requested changes

2021-02-20 18:07 UTC, matthi4s commented on src/Guild.js
> +class Guild {
Why are all functions static? You could create guild objects with the guild id etc., optionally with a get function and some form of cache.

2021-02-20 18:07 UTC, matthi4s commented on src/commands/legacy/strike.js
> +      ban.reason = reason; //DURATION DNW
What does that comment mean?

2021-02-20 18:07 UTC, matthi4s commented on src/commands/legacy/strike.js
> +      const ban = new Ban(/** @type {module:"discord.js".Message}*/{
You should probably separate the Ban itself from the command. "Faking" a command call is not really a clean solution.

2021-02-27 13:25 UTC, matthi4s requested changes

2021-02-27 13:25 UTC, matthi4s commented on src/commands/ban.js
> +const util = require('../util.js');
Shouldn't this file be deleted?

2021-02-27 13:25 UTC, matthi4s commented on src/Member.js
> +    async dmUser(verb, reason, duration) {
```suggestion
    async dmPunishedUser(verb, reason, duration) {
```

2021-03-07 17:50 UTC, KurtThiemann approved these changes

2021-03-07 17:53 UTC, matthi4s approved these changes

2021-03-07 17:53 UTC, merged