serverinfo command
aternosorg/modbot pull request #205
Opened 2021-02-25 20:20 UTC by BluewyDev

Please do let me know things i gotta fix or you want added

2021-02-26 10:38 UTC, Bloxigamer commented
Hello

2021-02-26 15:53 UTC, JulianVennen requested changes

2021-02-26 15:53 UTC, JulianVennen commented on src/commands/utility/serverinfo.js
> +        const embed = new Discord.MessageEmbed()
```suggestion
        const embed = new Discord.MessageEmbed();
```

2021-02-26 15:53 UTC, JulianVennen commented on src/commands/utility/serverinfo.js
> +            )
```suggestion
            );
```

2021-02-26 15:53 UTC, JulianVennen commented on src/commands/utility/serverinfo.js
> +                `**Owner:** ${guild.owner}\n**Owner ID:**\n${guild.ownerID}\n**Created:** ${guild.createdAt.toDateString()}\n**Region:** ${guild.region}\n**Guild ID:** ${guild.id}`,
You could first create a string (`let generic = '';`) and then assign each line separately (e.g. generic += `**Owner:** ${guild.owner} \n`;) 
then you can put them each in a separate line

2021-02-26 15:53 UTC, JulianVennen commented on src/commands/utility/serverinfo.js
> +                `**Owner:** ${guild.owner}\n**Owner ID:**\n${guild.ownerID}\n**Created:** ${guild.createdAt.toDateString()}\n**Region:** ${guild.region}\n**Guild ID:** ${guild.id}`,
guild.owner returns a GuildMember object: https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=owner

2021-02-26 15:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aternosorg/modbot?pullRequest=205) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/aternosorg/modbot?pullRequest=205) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: BluewyDev<br/>:x: Drachionix<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aternosorg/modbot?pullRequest=205) it.</sub>

2021-02-26 16:01 UTC, JulianVennen commented on src/commands/utility/serverinfo.js
> +            await message.channel.send(embed);
```suggestion
            await this.message.channel.send(embed);
```

2021-02-27 13:35 UTC, BluewyDev commented
Refer to my newest pr for the serverinfo command

2021-02-27 13:35 UTC, closed without merging