refactor clear moderations command
aternosorg/modbot pull request #219
Opened 2021-03-08 10:52 UTC by JulianVennen

2021-03-08 14:39 UTC, KurtThiemann requested changes

2021-03-08 14:39 UTC, KurtThiemann commented on src/User.js
> +    async fetch(client) {
Maybe make client a property of user instead?
like `new User(id, client)`

2021-03-08 14:39 UTC, KurtThiemann commented on src/commands/moderation/ClearModerations.js
> +        const count = moderations[0]["COUNT(id)"];
```suggestion
        const moderations = await this.database.queryAll("SELECT COUNT(id) as modCount FROM moderations WHERE userid = ? AND guildid = ?",[user.id,this.message.guild.id]);
        const count = moderations[0]["modCount"];
```

2021-03-09 16:20 UTC, KurtThiemann approved these changes

2021-03-17 08:56 UTC, matthi4s approved these changes

2021-03-17 08:57 UTC, merged