Create roleinfo command
aternosorg/modbot pull request #290
Opened 2021-06-12 09:36 UTC by FlitzDev

2021-06-12 09:43 UTC, FlitzDev commented
Should mention that this is what it looks like:
![image](https://user-images.githubusercontent.com/34064010/121772020-396c2b80-cb73-11eb-99f7-5af16b161a8b.png)
![image](https://user-images.githubusercontent.com/34064010/121772035-45f08400-cb73-11eb-8d6b-4bbe1d425aab.png)
![image](https://user-images.githubusercontent.com/34064010/121772048-56a0fa00-cb73-11eb-8e2a-47420736451d.png)

2021-06-13 12:03 UTC, JulianVennen requested changes

2021-06-13 12:03 UTC, JulianVennen commented on src/commands/utility/RoleInfoCommand.js
> +
this is indented one step too far

2021-06-13 12:03 UTC, JulianVennen commented on src/commands/utility/RoleInfoCommand.js
> +          const e = new Discord.MessageEmbed()
```suggestion
          const embed = new Discord.MessageEmbed()
```

2021-06-13 12:03 UTC, JulianVennen commented on src/commands/utility/RoleInfoCommand.js
> +          await message.channel.send(e)
```suggestion
          await message.channel.send(embed);
```

2021-06-13 12:03 UTC, JulianVennen commented on src/commands/utility/RoleInfoCommand.js
> +              .setDescription(`
you shouldn't stretch a string over multiple lines. Use \n and + to concat multiple strings

2021-06-13 18:55 UTC, JulianVennen commented on src/commands/utility/RoleInfoCommand.js
> +      } if (!role.permissions.has('ADMINISTRATOR')) {
```suggestion
      } 
      if (!role.permissions.has('ADMINISTRATOR')) {
```

2021-06-13 18:57 UTC, JulianVennen requested changes

2021-06-13 18:57 UTC, JulianVennen commented on src/commands/utility/RoleInfoCommand.js
> +      } if (!permissions) {
```suggestion
      } 
      if (!permissions) {
```

2021-06-13 18:57 UTC, JulianVennen commented on src/commands/utility/RoleInfoCommand.js
> +      }
```suggestion
          await this.message.channel.send(embed);
      }
```

2021-06-13 18:57 UTC, JulianVennen commented on src/commands/utility/RoleInfoCommand.js
> +      let role = this.message.guild.roles.resolve(this.args[0]);
you could also accept role mentions by using util.roleMentionToId

2021-06-14 20:54 UTC, JulianVennen approved these changes

2021-06-14 20:54 UTC, merged