limit reasons sent in discord api calls to under 512 characters
aternosorg/modbot pull request #389
Opened 2021-10-12 19:11 UTC by JulianVennen

2021-10-14 11:34 UTC, KurtThiemann requested changes

2021-10-14 11:34 UTC, KurtThiemann commented on src/Member.js
> +            reason: `${moderator.username}#${moderator.discriminator} ${duration ? `(${util.secToTime(duration)}) ` : ''}| ${reason}`.substring(0, 500) + '...'
You shouldn't add '...' to messages if the character limit was not exceeded

2021-10-17 03:38 UTC, Kaluub requested changes
Instead of `${moderator.username}#${moderator.discriminator}`, using `${moderator.tag}` where applicable would be shorter & more readable

2021-10-17 18:48 UTC, KurtThiemann approved these changes

2021-10-17 19:14 UTC, merged