Lock
aternosorg/modbot pull request #92
Opened 2020-09-01 18:58 UTC by JulianVennen

2020-09-01 19:57 UTC, KurtThiemann requested changes

2020-09-01 19:57 UTC, KurtThiemann commented on commands/lock.js
> +    let updates = '';
```suggestion
    let updates = [];
```

2020-09-01 19:57 UTC, KurtThiemann commented on commands/lock.js
> +        updates += `<#${channel.id}>, `;
```suggestion
        updates.push(`<#${channel.id}>`);
```

2020-09-01 19:57 UTC, KurtThiemann commented on commands/lock.js
> +      await message.channel.send(`Locked ${updates.substring(0,updates.length - 2)}!`);
```suggestion
      await message.channel.send(`Locked ${updates.join(', ')}!`);
```

2020-09-01 19:57 UTC, KurtThiemann commented on commands/lock.js
> +    let updates = '';
```suggestion
    let updates = [];
```

2020-09-01 19:57 UTC, KurtThiemann commented on commands/lock.js
> +        updates += `<#${channel.id}>, `;
```suggestion
        updates.push(`<#${channel.id}>`);
```

2020-09-01 19:57 UTC, KurtThiemann commented on commands/lock.js
> +      await message.channel.send(`Locked ${updates.substring(0,updates.length - 2)}!`);
```suggestion
      await message.channel.send(`Locked ${updates.join(', ')}!`);
```

2020-09-01 19:57 UTC, KurtThiemann commented on commands/unlock.js
> +    let updates = '';
```suggestion
    let updates = [];
```

2020-09-01 19:57 UTC, KurtThiemann commented on commands/unlock.js
> +        updates += `<#${channel.id}>, `;
```suggestion
        updates.push(`<#${channel.id}>`);
```

2020-09-01 19:57 UTC, KurtThiemann commented on commands/unlock.js
> +    await message.channel.send(`Unlocked ${updates.substring(0,updates.length - 2)}!`);
```suggestion
    await message.channel.send(`Unlocked ${updates.join(', ')}!`);
```

What if no channels were unlocked (updates.length === 0)?

2020-09-01 19:57 UTC, KurtThiemann commented on commands/unlock.js
> +    let updates = '';
```suggestion
    let updates = [];
```

2020-09-01 19:57 UTC, KurtThiemann commented on commands/unlock.js
> +        updates += `<#${channel.id}>, `;
```suggestion
        updates.push(`<#${channel.id}>`);
```

2020-09-01 19:57 UTC, KurtThiemann commented on commands/unlock.js
> +      await message.channel.send(`Unlocked ${updates.substring(0,updates.length - 2)}!`);
```suggestion
      await message.channel.send(`Unlocked ${updates.join(', ')}!`);
```

2020-09-02 16:20 UTC, KurtThiemann commented on commands/unlock.js
> +    await message.channel.send(`Unlocked ${updates.substring(0,updates.length - 2)}!`);
?

2020-09-02 16:21 UTC, matthi4s requested changes

2020-09-02 16:21 UTC, matthi4s commented on commands/lock.js
> +command.description = 'Dissallow users to send messages to a channel';
```suggestion
command.description = 'Disallow users to send messages to one or multiple channels';
```

2020-09-02 16:21 UTC, matthi4s commented on commands/lock.js
> +  let embed = new Discord.MessageEmbed().setTitle('This channel has been locked!').setDescription(args.join(' ')).setColor(util.color.red);
```suggestion
  let embed = new Discord.MessageEmbed().setTitle('This channel is locked.').setDescription(args.join(' ')).setColor(util.color.red).setFooter('You are not muted, this channel is locked for everyone. Don't send direct messages to team members or moderators .');
```
(Or a similar footer text, not sure about the exact wording yet.)

2020-09-02 16:32 UTC, matthi4s commented on commands/lock.js
> +    let embed = new Discord.MessageEmbed().setTitle('This channel has been locked!').setDescription(args.join(' ')).setColor(util.color.red);
```suggestion
```

2020-09-02 16:36 UTC, matthi4s commented on commands/lock.js
> +      o[p] = false;
Don't call variables `o` and `p`.

2020-09-02 16:43 UTC, matthi4s commented on commands/lock.js
> +  let embed = new Discord.MessageEmbed().setTitle('This channel is locked.').setDescription(args.join(' ')).setColor(util.color.red).setFooter('You are not muted, this channel is locked for everyone.
```suggestion
  let embed = new Discord.MessageEmbed().setTitle('This channel is locked.').setDescription(args.join(' ')).setColor(util.color.red).setFooter('You are not muted, this channel is locked for everyone. Don\'t send direct messages to team members or moderators .');
```

2020-09-03 17:03 UTC, matthi4s approved these changes

2020-09-03 17:05 UTC, JulianVennen commented on commands/unlock.js
> +    await message.channel.send(`Unlocked ${updates.substring(0,updates.length - 2)}!`);
hatte den kommentar übersehen habs gefixt

2020-09-03 18:02 UTC, KurtThiemann approved these changes

2020-09-03 18:03 UTC, merged