no moderations message
aternosorg/modbot pull request #94
Opened 2020-09-02 14:14 UTC by JulianVennen

2020-09-02 16:05 UTC, KurtThiemann requested changes

2020-09-02 16:05 UTC, KurtThiemann commented on commands/moderations.js
> +      description: 'This user doesnt have any moderations!'
```suggestion
      description: 'This user doesn't have any moderations!'
```

2020-09-02 16:09 UTC, matthi4s approved these changes

2020-09-03 14:52 UTC, KurtThiemann approved these changes

2020-09-03 14:52 UTC, merged